spring:
  datasource:
    url: jdbc:mysql://localhost:33060/mysql_docker
    username: root
    password: apirest
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

server:
    port: ${PORT:8002}
    
springdoc:
    swagger-ui:
      enabled: true